AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'doc/**/*'
    - 'docker_app/**/*'
    - 'Guardfile'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'playground/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'

# Models can have a bunch of attributes which lead to long methods and high
# complexity values. However, these methods are still very readable because they
# usually have a lot of repetition.
Metrics:
  Exclude:
    - 'db/migrate/*.rb'

# We need to configure exemptions for blocks that we generally accept to be
# long, since they are less comparable to methods and more comparable to
# modules/classes.
Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - namespace
    - factory
    - define
    - shared_examples_for
    - shared_examples
    - xcontext
    - xdescribe
  Exclude:
    - 'config/environments/*.rb' # instead of excluding all :configure methods
    - 'config/routes.rb'
    - 'spec/spec_helper.rb' # instead of excluding all :configure methods
    - '*.gemspec' # a gemspec could easily have more than the 25 lines limit


Metrics/MethodLength:
  Max: 16

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: true
  Exclude:
    - '*.gemspec'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false
